### ISSUE TITLE
Improve installation steps described in readme.

### ISSUE THREAD

**Issue by GrzegorzDrozd** [cgd-ui/genealogy#218]
I have installed backend project in a directory. I downloaded UI project into a directory. Using node 14 (I had to guess the version) I managed to perform yarn install. I have no idea what do do next.

Please provide clear and easy to follow instructions how to connect to backend, where should I point my document root from webserver. Where can I configure anything. Which versions of node, npm etc are tested and can be used on prod.

**Comment by curtisdelicata** [comment]
master is in development for nuxt 3 and vue 3.
nuxt2 branch is stable.

**Comment by curtisdelicata** [comment]
yarn install then yarn build to generate static files or yarn dev for hot reload

**Comment by curtisdelicata** [comment]
I've switched nuxt2 to master to make it easier.
